### ISSUE TITLE
Improve the design a little bit

### ISSUE THREAD

**Issue by volodymyr-kushnir** [denterekhov/homepage#15]
![screencapture-denterekhov-github-io-homepage-2019-05-12-19_06_06](https://user-images.githubusercontent.com/10290626/57585492-319bb200-74e9-11e9-9f50-1f1fbdcf916e.png)
Darth Vader мав би бути чорнобілим, максимум червоним в деяких місцях (але в деяких, не "системних"). Я б використовував `<ol class="inverted">` для "Ліцензій і сертифікацій". І було б круто якби в "Objectives" та "Interests and hobbies" іконки переставити наліво замість буллетів списку.

**Comment by denterekhov** [comment]
@volodymyr-kushnir Done!
