### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by denterekhov** [denterekhov/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by denterekhov** [comment]
**Pod Engine Scrubber (Watto's General Merchandise, Inc.)**
- Worked independently to achieve daily quota of repaired engine parts
- Provided flexible support to other departments of store as needed

 
**Loss-Prevention Officer (Watto's General Merchandise, Inc.)**
- Processed unusual financial transactions
- Defended merchandise against potential theft on a daily basis
- Improved knowledge of useful professional skills (gambling, embezzlement, fraud, et al.)

**Caf Acquisition Officer (Jedi Council)**
- Personally filled Mace Windu's caf mug up to twelve times per day
- Developed mental agility in order to remember twelve separate caf orders while running down fifty-two flights of stairs to Temple Cafeteria

 
**Shaak Traffic Controller (Naboo Ministry of Nature Preservation)**
- Directed and re-directed large herds of shaak in accordance with the directives of senior Nubian government officials, at great personal risk

**Intern (Office of Senator Padmé Amidala)**
- Studied galactic-level political figures on a highly intimate level
- Enjoyed extensive personal involvement in Senator Amidala's work
- Capably and creatively met Senator Amidala's miscellaneous needs

 
**Tea Production Manager (Grand Army of the Republic)**
- Personally filled Obi-Wan Kenobi's teacup up to thirty-one times per standard day
- Mastered art of brewing sixty-four varieties of tea efficiently while under fire and orbital bombardment

 
**General (Grand Army of the Republic)**
- Commanded crack infantry and starfighter squadrons in a variety of combat situations against extreme odds
- Trained Jedi Padawans in the GAR Accelerated Officer Training Program
- Won several dozen critical engagements. What.

**Master (Jedi Order)**
- Learned to work with young people to the best of their admittedly limited ability.
- Capably dealt with difficult situations such as temper tantrums, teamwork on battlefields, insubordination, "women's issues", etc, etc.

 
**General Manager (Imperial Jedi Extermination Services)**
- Coordinated and executed the elimination of 10,000+ enemies of the state over the course of two years
- Reduced operating costs by 62% through creative cost-cutting measures such as mass executions and use of energy-efficient weaponry

**Personal Assistant (Office of the Galactic Emperor)**
- Personally filled His Imperial Majesty's hot chocolate mug at least fifty times per week
- Assumed progressive responsibility for approximately 35% of all Imperial governing decisions, including but not limited to military operations, intelligence agencies, selective elimination of inconvenient persons, environmental disasters, charitable donations, and office supply acquisition for fourteen bureaucratic ministries

**Commander-in-Chief (Imperial Armed Forces)**
- Exercised direct, total, absolute, irrevocable, and unequivocal command of the Imperial Navy, Army, Marines, and Merchant Marines, comprising over seventeen trillion Imperial military personnel, fifty trillion droid personnel, and an estimated google of civilian adjuncts
- Honorary President of Imperial Military Academy of Carida
- De Facto Heir to Imperial Throne
- Official hot chocolate-maker to His Imperial Majesty the Emperor

**Comment by volodymyr-kushnir** [comment]
@denterekhov добре, але мало. більше → https://archiveofourown.org/works/8104921

**Comment by denterekhov** [comment]
@volodymyr-kushnir  айс! те, що треба.
